name: Reusable workflow example

on:
  push:
  workflow_call:
jobs:
  print-username:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10, 12, 14 ]
    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}