name: Reusable workflow example

on:
  push:
  workflow_call:

jobs:
  get_test_classes:
    name: get test classes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10, 12, 14 ]
    steps:
      # Configures the node version used on GitHub-hosted runners
      - run: echo ${{ matrix.node }}



