name: Reusable workflow example

on:
  push:
  workflow_call:

jobs:
  getAllTestFiles:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: bash ./.github/scripts/getFiles.sh
        shell: bash
  RunAllTestFiles:
    needs: getAllTestFiles
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.getAllTestFiles.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.path }}
      - run: echo ${{ matrix.name }}
